spring.application.name=Event_Ticketing_System
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5499/postgres
spring.datasource.username=vanneth
spring.datasource.hikari.password=vanneth
server.port=9000
